AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template para EcoDanva Solutions - S3 y CloudFront.

Resources:
  # Bucket S3 para el sitio web estático
  EcoDanvaWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: eco-danva-solutions-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
        IgnorePublicAcls: false

  # Política del Bucket para acceso público
  EcoDanvaBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EcoDanvaWebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${EcoDanvaWebsiteBucket.Arn}/*"

  # Distribución CloudFront para el contenido de S3
  EcoDanvaCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt EcoDanvaWebsiteBucket.RegionalDomainName
            Id: EcoDanvaS3Origin
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: EcoDanvaS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: ["GET", "HEAD"]
          CachedMethods: ["GET", "HEAD"]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100

Outputs:
  S3BucketName:
    Description: Nombre del bucket S3 creado
    Value: !Ref EcoDanvaWebsiteBucket

  S3WebsiteURL:
    Description: URL del sitio web en el bucket S3
    Value: !GetAtt EcoDanvaWebsiteBucket.WebsiteURL

  CloudFrontDomainName:
    Description: URL de la distribución de CloudFront
    Value: !GetAtt EcoDanvaCloudFrontDistribution.DomainName
