name: Upload Static Files to S3

on:
  push:
    paths:
      - '**'           # Ejecutar cuando cualquier archivo cambie
  workflow_dispatch:   # Permite ejecución manual desde la pestaña Actions

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Subir archivos al bucket S3, excluyendo no deseados
      - name: Upload project files to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.S3_BUCKET_NAME }} --acl public-read \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "cf-resources-template.yaml"
